### ISSUE TITLE
Proper mobile navigation

### ISSUE THREAD

**Issue by pawcoding** [pawcoding/Rainbow-Palette#26]
The current implementation of the navigation bar feels a bit clunky on mobile. It would be nice to have a proper bottom navigation bar, as is the case with native apps.

**Comment by alanbosco003** [comment]
can you please assign this issue to me?

**Comment by pawcoding** [comment]
We could also leave the navigation in the header and make something looking like this. I kinda like this look.

![Mobile Navigation](https://user-images.githubusercontent.com/78467484/233850564-0e66d64b-f1e9-49bc-b963-a61e42ec5017.png)

**Comment by pawcoding** [comment]
Closing now because I implemented this in the complete rewrite
